"""add nullable for category_id

Revision ID: 8d92a112b72c
Revises: 20b13fc8738b
Create Date: 2026-03-25 16:06:47.116581

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "8d92a112b72c"
down_revision: Union[str, Sequence[str], None] = "20b13fc8738b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
