version: '0.2'

services:
  redis:
    image: redis:8.4.2
    container_name: habbit_tracker_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  kafka:
    image: apache/kafka:4.1.1
    container_name: habbit_tracker_kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data
    ports:
      - "9092:9092"
    restart: unless-stopped

  clickhouse:
    image: clickhouse/clickhouse-server:26.1
    container_name: habbit_tracker_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: habbit_tracker_db
    env_file:
      - .env
    ports:
      - 5472:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  kafka_data:
  clickhouse_data:

networks:
  default:
    name: habbit_network