version: '0.2'

services:
  redis:
    image: redis
    container_name: habbit_tracker_redis
    ports:
      - "6379:6379"
    restart: unless-stopped


  db:
    image: postgres:15
    container_name: habbit_tracker_db
    env_file:
      - .env
    ports:
      - 5472:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: